spring:
  application:
    name: service-hello
  cloud:
    config:
      #访问config server的地址
      uri: http://localhost:8001
      #对应config server中配置文件的{profile}
      profile: dev
      #对应config server中配置文件的{label}
      label: master
